FROM bitnamilegacy/spark:3.5.0

USER root

RUN pip install --no-cache-dir \
    numpy==1.26.4 \
    pandas==2.1.4 \
    pyarrow==14.0.2 \
    onnxruntime==1.16.3 \
    joblib==1.3.2 \
    scikit-learn==1.4.2

USER 1001