FROM bitnamilegacy/spark:3.5.0

# Temporarily switch to root to install python packages
USER root

# Install Python dependencies required for Pandas UDFs and ONNX inference
RUN pip install --no-cache-dir \
    pandas==2.1.1 \
    pyarrow==13.0.0 \
    onnxruntime==1.16.0

# Revert to the non-root user (Bitnami standard UID is 1001)
USER 1001
